### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by chenyu1330** [AlexanderFrotscher/ANDi#3]
Hello, thank you very much for your wonderful work, but I didn't find these two datasets, MSSEG and Ljubljana MS lesion datasets, on the Internet. Can you provide a download link?

**Comment by AlexanderFrotscher** [comment]
Hey, these two are datastes that you would need to apply for. I got them from the Shifts challenge https://shifts.grand-challenge.org/medical-dataset/  .
Maybe they are not handing data out anymore, so maybe it is not possible to actually obtain the data. MSSEG might be available here: https://portal.fli-iam.irisa.fr/msseg-challenge/english-msseg-data/
I personally can not provide a download link since it is not allowed to do this.
